content: 
  command: pet
  probability: 30
  antialias: true
  disabled: []
  commandHead: ''
  respondSelfNudge: false
  respondReply: true
  cachePoolSize: 10000
  keyListFormat: FORWARD
  disablePolicy: NUDGE
  fuzzy: false
  strictCommand: true
  synchronized: false
  headless: true
  autoUpdate: true
  updateIgnore: []
  repositoryUrl: 'https://dituon.github.io/petpet'